### ISSUE TITLE
"fa_svg" error

### ISSUE THREAD

**Issue by roomylee** [sergiokopplin/indigo#416]
I got a message like the below and my github page not working because of it.

> Your site is having problems building: The tag fa_svg on line 14 in _includes/author.html is not a recognized Liquid tag.

Is there any problem about "fa_svg" tag or font awesome svg ?

**Comment by sergiokopplin** [comment]
Hey @roomylee 

Have you tried to update your branch with the current one from indigo?
I've seen few differences between your code and Indigos more updated branch. 

Can you update, run the readme and test it again?
Let me close for now.

**Comment by roomylee** [comment]
Thank you for your reply @sergiokopplin 
i already have latest branch(gh-pages) version. (and gh-pages renamed master in my repo. refer to #396 )
In my local environment, it work well. but unfortunately it does not work on github page...

**Comment by sergiokopplin** [comment]
Weird. It seems that you're the first with this problem.
I'm not sure how to fix this. I've made a search about this issue and found nothing relevant.

We need more testing on this.

**Comment by roomylee** [comment]
@sergiokopplin really appreciate 
Thank you for your attention. I hope to solve this problem soon.

**Comment by kunalbotla** [comment]
> Thank you for your reply @sergiokopplin
> i already have latest branch(gh-pages) version. (and gh-pages renamed master in my repo. refer to #396 )
> In my local environment, it work well. but unfortunately it does not work on github page...

My issue is the exact same.

**Comment by Jangmin-Lee** [comment]
Same here

**Comment by KaustubhSathe** [comment]
same here

**Comment by sergiokopplin** [comment]
I've merged a PR. can you guys check if it works?

**Comment by kuantingchen04** [comment]
Sorry for the inconvenience. I found the problem still exists and the it occurs since a83f71f786a5bd70797e60e11bfc4c26985b6fba. 

I think the plugin `jekyll-fontawesome-svg` might not be supported on Github Pages.  
Here is a list of its [supported plugins](https://pages.github.com/versions/). For more details please check [here](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins)

Removing the tags may be the easiest solution. Or you'll need to generate the site locally and then push the static files to GitHub.



> I've merged a PR. can you guys check if it works?

**Comment by KaustubhSathe** [comment]
still not working

**Comment by sergiokopplin** [comment]
I'll check it later

**Comment by JiaqiWang1107** [comment]
the same problem

**Comment by jayloofah** [comment]
There ought to be a fix I feel (other sites use this I'm sure).

**Comment by JiaqiWang1107** [comment]
[image: Screen Shot 2020-02-26 at 5.15.02 PM.png]

**Comment by JiaqiWang1107** [comment]
The page build failed for the `gh-pages` branch with the following error:

The tag `fa_svg` on line 14 in `_includes/author.html` is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

**Comment by ekercaglar** [comment]
Same problem

**Comment by sergiokopplin** [comment]
I'm looking into this, i don't have a solution yet. 
I was thinking about removing the liquid tag from that specific file and updating it with a html tag instead. What you guys think? It will generate the favicon html, it will render with the css class and I think it will work. I didn't test it yet.

**Comment by dadadima** [comment]
I think you can do it that way. btw, I do also have the same problem, which one is the latest stable release?

**Comment by sylvainmetayer** [comment]
Hello, 

I'm the author of the PR #338 that seems to break site with github page. As I don't use Github page to deploy my site, I don't have this bug. Sorry about this :disappointed: 

I see 2 solutions : 

- Remove this PR and go back to one HTML file, less flexible but it worked before.
- Try to see what github actions could do with this. I'm thinking about adding [this action](https://github.com/helaili/jekyll-action) or [this one](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages) to build the site on master, and then having the action building and pushing the generated code (with this gem) on gh-page. It *may* work as a workaround to use unsupported jekyll extension on github page.

**Comment by JiaqiWang1107** [comment]
Thanks for your effort!

If possible, could you please add another version of the whole website that
could be run on Github? That might be easier for beginners like me. Thank
you!

**Comment by jayloofah** [comment]
> Hello,
> 
> I'm the author of the PR #338 that seems to break site with github page. As I don't use Github page to deploy my site, I don't have this bug. Sorry about this 😞
> 
> I see 2 solutions :
> 
>     * Remove this PR and go back to one HTML file, less flexible but it worked before.
> 
>     * Try to see what github actions could do with this. I'm thinking about adding [this action](https://github.com/helaili/jekyll-action) or [this one](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages) to build the site on master, and then having the action building and pushing the generated code (with this gem) on gh-page. It _may_ work as a workaround to use unsupported jekyll extension on github page.

@sylvainmetayer what are you using to deploy?

**Comment by sylvainmetayer** [comment]
> > Hello,
> > I'm the author of the PR #338 that seems to break site with github page. As I don't use Github page to deploy my site, I don't have this bug. Sorry about this disappointed
> > I see 2 solutions :
> > ```
> > * Remove this PR and go back to one HTML file, less flexible but it worked before.
> > 
> > * Try to see what github actions could do with this. I'm thinking about adding [this action](https://github.com/helaili/jekyll-action) or [this one](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages) to build the site on master, and then having the action building and pushing the generated code (with this gem) on gh-page. It _may_ work as a workaround to use unsupported jekyll extension on github page.
> > ```
> 
> @sylvainmetayer what are you using to deploy?

I host it on my raspberry and using travis CI to build and deploy

@sergiokopplin  @JiaqiWang1107 I'll try to submit a PR on *master* this weekend to fix this.

**Comment by sergiokopplin** [comment]
Nice @sylvainmetayer! The font-awesome feature seems to be necessary! So, if you can, don't remove that, try first something that fix the problem instead of removing the feature. What do you think>

**Comment by sylvainmetayer** [comment]
I've been looking at [this action](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages) and with some edits, I've managed to build and deploy a site from master branch, to gh-pages branch, while building with jekyll-fontawesome gem.

@sergiokopplin Can you create a master branch so I can propose a PR against it with the github action setup ? 

Their is maybe some details to work on, such as paths (which seems for now to link to the main repo) and maybe others minor fix. 

See current work here : https://sylvainmetayer.github.io/indigo/

**Comment by sergiokopplin** [comment]
@sylvainmetayer really nice work! well done.

I'm thinking about this solution, and it seems to be complicated for new users. In my opinion Indigo should be simple, and now it's too difficult. This new action to deploy adds another layer for the users to learn how to have a personal website running. 

The solution is great, modern and has new technologies from github, awesome!
But, the solution is not easy to understand, you must generate a token, give some access, etc. Not easy at all.

What do you think? Can we find another solution for that? We can disagree, but help me think about an easy solution!

@sylvainmetayer your jekyll plugin is great, btw.

cc @jehartzog @mehmandarov

**Comment by sergiokopplin** [comment]
Btw, I've tested removing the tag and creating the html tag. It doesn't work because we don't actually load the font-awesome font files. So, we need to find another way.

**Comment by sylvainmetayer** [comment]
> Btw, I've tested removing the tag and creating the html tag. It doesn't work because we don't actually load the font-awesome font files. So, we need to find another way.

If we want to keep the fontawesome gem, we'll have to use GitHub actions or a different build system than the one we use now, the gem will probably never be whitelisted to be used with GitHub pages natively. The only workaround is to rollback the PR, and adding back fontawesome icons one by one.


> The solution is great, modern and has new technologies from github, awesome!
> But, the solution is not easy to understand, you must generate a token, give some access, etc. 

Their is no additional setup for the user, no token to generate, the workflow is still the same, clone and you're ready to go :)
The only difference is that we work on master branch now, not in gh-pages.

Is that good to you?

**Comment by sergiokopplin** [comment]
Maybe I've made a mistake then. 

![image](https://user-images.githubusercontent.com/2743180/76234833-0406be80-6209-11ea-8ad1-2e510f9ff1c6.png)

I thought it would be necessary.

Let's try your approach with the master branch. @sylvainmetayer

**Comment by sergiokopplin** [comment]
@sylvainmetayer Master Branch available. What else do you need?

**Comment by sylvainmetayer** [comment]
> Maybe I've made a mistake then.
> 
> ![image](https://user-images.githubusercontent.com/2743180/76234833-0406be80-6209-11ea-8ad1-2e510f9ff1c6.png)
> 
> I thought it would be necessary.
> 
> Let's try your approach with the master branch. @sylvainmetayer

Yes I've been confused while testing, though we would need one token too but seem GitHub auto provide one at runtime named "GitHub_token" and it works well.

I need nothing else, I will provide the pull request soon!

**Comment by sylvainmetayer** [comment]
Pull request submitted. 

One thing to notice : all users will have to rebase from master branch and use master branch from now. Maybe we should consider making a release after merging and announcing some breaking change for existing users?

**Comment by sergiokopplin** [comment]
Yeah, that makes sense! Let's test it, then we can think about making a release.

**Comment by sergiokopplin** [comment]
I've added you as a collaborator @sylvainmetayer

**Comment by sergiokopplin** [comment]
Merged @sylvainmetayer

**Comment by sylvainmetayer** [comment]
> Yeah, that makes sense! Let's test it, then we can think about making a release.

Sadly it seems that this didn't solve our issue :disappointed: 

I'll look into it during the week, when I'll have a moment.

**Comment by sylvainmetayer** [comment]
Build site is correctly pushed to github pages branch, but I don't know why Github page jobs run before github actions :cry: 

However, the site seems to be build, even in error... Strange, we'll have to look into it

**Comment by sergiokopplin** [comment]
I'm also looking into that!

**Comment by sylvainmetayer** [comment]
[This](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/31266/highlight/true#M743) could be an hint, and would require to edit the action I've used ([here](https://github.com/sylvainmetayer/jekyll-deploy-gh-pages))

**Comment by sylvainmetayer** [comment]
@sergiokopplin I've done some testing, and after forcing first update (by triggered an other with an useless commit, we could also have done that using github API), it seems to work now. See https://koppl.in/indigo/about/ and 06bd5ba4088347dbc832f8887c924c0f57d268d7 done right now, it seems to me that it is ok ?

**Comment by gforghieri** [comment]
Hi @sergiokopplin and @sylvainmetayer,

I can confirm that the fix suggested by @sylvainmetayer  successfully deploys the site on Github 
Pages. https://gforghieri.github.io/


**The steps to follow**:

1. Fork the repo
2. Make any changes e.q. add an extra line to the readme.md and commit it to trigger the GitHub Actions to run. The Github Actions are using the `.github/workflows/main.yml` file which uses https://github.com/sylvainmetayer/jekyll-deploy-gh-pages which is forked from https://github.com/marketplace/actions/jekyll-deploy-gh-pages  
3. When the Github Actions complete the job in the pipeline, the site is up and running.

**To give a bit of context:**
I've recently come across the Indigo theme.
I've wanted to create a new personal website and have been looking around for a while.

This morning I decided to make it happen. 
Ran into the same problem as described in this issue.

![image](https://user-images.githubusercontent.com/23422651/76443769-41af4700-63c3-11ea-9aa7-eb90d7677f16.png)

**Comment by gforghieri** [comment]
To add,

Even though it is a solution, I agree with @sergiokopplin that it is not a user-friendly one and the building of the site takes quite long this way.

So this should be fixed such that there is native support for Github Pages.

**Comment by sylvainmetayer** [comment]
Hi @gforghieri and sorry for the setup trouble ! I'm glad you finally succeeded to make it work however. 

> Even though it is a solution, I agree with @sergiokopplin that it is not a user-friendly one and the building of the site takes quite long this way.
> 
> So this should be fixed such that there is native support for Github Pages.

I think this gem plugin will never be whitelisted on github pages. The only solution to fix this is to remove the gem and go back the way it was before, where their was a lot of conditionnal state and svg where manually defined.

**Comment by jayloofah** [comment]
Hmm, is it possible to host on Gitlab without error using this method?

**Comment by sylvainmetayer** [comment]
@jayloofah I don't think so, you'll have the same issue on gitlab, I guess gitlab page too use whitelisted gems only

**Comment by sylvainmetayer** [comment]
@sergiokopplin What do you think we should do ? Rollback the PR and go back as it was before ? Or consider the github actions a good enough option ?

**Comment by kunalbotla** [comment]
@sergiokopplin and @sylvainmetayer, what exactly is the fix. I'm not sure how exactly it works. I feel making it user-friendly to deploy to GitHub Pages is the best option.

**Comment by mehmandarov** [comment]
@sergiokopplin and @sylvainmetayer: Yes, I think at this point it is better to revert to change while you work on separate branch with this feature?

**Comment by sylvainmetayer** [comment]
@kunalbotla 

> I feel making it user-friendly to deploy to GitHub Pages is the best option.

I agree too, the fix I've tried should be "clone and you're ready to go with github page and github actions auto-configured" but I need more feedback too see if it is reliable or not.

If not, we'll have to rollback and remove this PR because their is no other fix for this. The gem will never be allowed on github page, we'll have to rewrite it the way it was before and include manually wanted svg icons.

**Comment by Jun0413** [comment]
> @kunalbotla
> 
> > I feel making it user-friendly to deploy to GitHub Pages is the best option.
> 
> I agree too, the fix I've tried should be "clone and you're ready to go with github page and github actions auto-configured" but I need more feedback too see if it is reliable or not.
> 
> If not, we'll have to rollback and remove this PR because their is no other fix for this. The gem will never be allowed on github page, we'll have to rewrite it the way it was before and include manually wanted svg icons.

Hi @sylvainmetayer 

Thanks for your great work. I am new to Jekyll, but am able to go through your commits and trigger the action to build my GitHub page. You may visit it on `jun0413.github.io/indigo`.

In addition to using GitHub action, I would like to share a problem that I ran into. To use the `gh-page` branch, I changed the repository name to `indigo` instead of `<username>.github.io`. I can enter the index page, but I cannot enter blog or project pages, because the url to blog page is `<username>.github.io/blog`. So in `_config.yml`, we need to set the url to be `<username>.github.io/indigo`

**Comment by Zeyuzhao** [comment]
> Hi @sergiokopplin and @sylvainmetayer,
> 
> I can confirm that the fix suggested by @sylvainmetayer successfully deploys the site on Github
> Pages. https://gforghieri.github.io/
> 
> **The steps to follow**:
> 
> 1. Fork the repo
> 2. Make any changes e.q. add an extra line to the readme.md and commit it to trigger the GitHub Actions to run. The Github Actions are using the `.github/workflows/main.yml` file which uses https://github.com/sylvainmetayer/jekyll-deploy-gh-pages which is forked from https://github.com/marketplace/actions/jekyll-deploy-gh-pages
> 3. When the Github Actions complete the job in the pipeline, the site is up and running.
> 
> **To give a bit of context:**
> I've recently come across the Indigo theme.
> I've wanted to create a new personal website and have been looking around for a while.
> 
> This morning I decided to make it happen.
> Run into the same problem as described in this issue.
> 
> ![image](https://user-images.githubusercontent.com/23422651/76443769-41af4700-63c3-11ea-9aa7-eb90d7677f16.png)

Hi @gforghieri
Could you show me how you used GitHub actions with your profile (https://gforghieri.github.io/) GitHub pages? When I used the utility, it compiled to gh-pages, which I could not use with my zeyuzhao.github.io repository. The settings indicate only the master branch could be used.

![image](https://user-images.githubusercontent.com/6325738/77969787-95bd9500-72b8-11ea-9b54-44f95a24ee79.png)

**Comment by Jun0413** [comment]
@Zeyuzhao Hi I think you need to use gh-page branch instead of the master branch. That said, you could not use zeyuzhao.github.io because it requires pages to be built from the master branch. My approach was to rename the repository from xxx.github.io to indigo, and set the site to build from gh-page branch, and the url will be xxx.github.io/indigo.

**Comment by Zeyuzhao** [comment]
@Jun0413 Thanks for the reply! Right now, I am following your approach (renaming my repo to **personal** and thus the url would be zeyuzhao.github.io/personal), but I would like to find out if there is an alternative approach to using just zeyuzhao.github.io for the name with this GitHub Action utility. 

I was thinking of modifying zeyuzhao.github.io's master branch in the same way the gh-pages is being modified (`git push --force`) in the jekyll-deploy-gh-pages [entrypoint.sh](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages/blob/master/entrypoint.sh), but that would be a messy hack at the best.

**Comment by Jun0413** [comment]
Hi @Zeyuzhao, I think to accomodate for that, you can try "swapping" master branch and gh-page branch. First of all, I am not sure whether GitHub will work in that way, but you can definitely reset your master branch. In such way, your old master branch becomes gh-page, your old gh-page branch becomes master branch. So you will modify on gh-page branch locally, and use GitHub action to build to the master branch, which'd require changing the deploy scripts. Personally, I am satisfied with `<username>.github.io/<reponame>`, because it does not fully take away the only domain name from GitHub page.

**Comment by sergiokopplin** [comment]
Hey guys! Awesome discussion! @sylvainmetayer let's go back to the older version?What do you think?

**Comment by sylvainmetayer** [comment]
Sure, let's do this.

@sergiokopplin I'll let you reverse the PR ?

**Comment by kunalbotla** [comment]
Has this been rolled back to the older PR without the problem?

**Comment by sylvainmetayer** [comment]
@sergiokopplin Did you get any time to take a look on this one ?

**Comment by sergiokopplin** [comment]
I'll take a look this week!
I'm changing jobs this week so I'm in a rush.
BTW, stay safe guys!

**Comment by sergiokopplin** [comment]
I've made several fixes. Can you guys check?

**Comment by kunalbotla** [comment]
It looks like it is working on GitHub Pages now. Why are the icons changed to this:

![image](https://user-images.githubusercontent.com/25641153/79677118-bdb75e80-81bb-11ea-8680-118fa61ca6ab.png)

**Comment by sergiokopplin** [comment]
Because we've removes fontawesome icons. We can have the fontawesome ones, but we need a new feature for that.

**Comment by sergiokopplin** [comment]
It seems to be solved then. Closing

**Comment by kunalbotla** [comment]
@sergiokopplin can the icons just be hosted locally?

**Comment by sergiokopplin** [comment]
@kunalbotla What do you mean by locally?

**Comment by kunalbotla** [comment]
Like having them as an asset that is downloaded and not use a plugin.
